### ISSUE TITLE
rephrase to clarify tasks and materials 

### ISSUE THREAD

**Issue by siandav** [ironhack-labs/lab-intro-sql#1]
@sandrabosk i worked through these instructions and had a go at rephrasing / adding more context 

Links to sakila instructions to load database - specific to your client or you could run from command line 
You can work with two sql query files - sakila-schema.sql (creates the schema) + sakila-data.sql inserts the data

The ERD is pictured above the instructions - not all tables are shown, but many of the key fields you will be using are visible 

1. Review the tables in the database.
2. Explore tables by selecting all columns from each table or using the in built review features for your client 
3. Select one column from a table:  Get film titles.
4. Select one column from a table and alias it : Get unique list of film languages under the alias ‘language’ -NOTE we are not asking you to  obtain the language per each film… but this is a good time to think about how you might get that information in the future. 
5. Using select statements and reviewing how many records are returned, can you find out how many stores and staff does the company have? Can you return a list of employee first names only? 
6. BONUS : How many unique days did customers rent movies in this dataset?

**Comment by ironhack-edu** [comment]
Updating the instructions @siandav, thank you. Can you please provide a solution for iteration 6 (bonus)?

**Comment by ironhack-edu** [comment]
@siandav [Solution file](https://gist.github.com/ironhack-edu/a7ae236289c245fe73b4e103546ec690) updated, ignore the previous request. Thanks.
